server:
  port: 5006

env: development
log:
  level: info

database:
  host: postgres
  port: 5433
  user: postgres
  password: postgres
  dbname: itcmdb
  sslmode: disable

jwt:
  secret: your-secret-key
  expiration: 24h
