// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/cmdb.proto

package cmdb

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCIInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIInstanceRequest) Reset() {
	*x = GetCIInstanceRequest{}
	mi := &file_proto_cmdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIInstanceRequest) ProtoMessage() {}

func (x *GetCIInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetCIInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{0}
}

func (x *GetCIInstanceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCIInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *CIInstance            `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIInstanceResponse) Reset() {
	*x = GetCIInstanceResponse{}
	mi := &file_proto_cmdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIInstanceResponse) ProtoMessage() {}

func (x *GetCIInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetCIInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{1}
}

func (x *GetCIInstanceResponse) GetInstance() *CIInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type GetCIInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiTypeId      uint32                 `protobuf:"varint,1,opt,name=ci_type_id,json=ciTypeId,proto3" json:"ci_type_id,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIInstancesRequest) Reset() {
	*x = GetCIInstancesRequest{}
	mi := &file_proto_cmdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIInstancesRequest) ProtoMessage() {}

func (x *GetCIInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetCIInstancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{2}
}

func (x *GetCIInstancesRequest) GetCiTypeId() uint32 {
	if x != nil {
		return x.CiTypeId
	}
	return 0
}

func (x *GetCIInstancesRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetCIInstancesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCIInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCIInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*CIInstance          `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIInstancesResponse) Reset() {
	*x = GetCIInstancesResponse{}
	mi := &file_proto_cmdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIInstancesResponse) ProtoMessage() {}

func (x *GetCIInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetCIInstancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetCIInstancesResponse) GetInstances() []*CIInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *GetCIInstancesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCITypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCITypeRequest) Reset() {
	*x = GetCITypeRequest{}
	mi := &file_proto_cmdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCITypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCITypeRequest) ProtoMessage() {}

func (x *GetCITypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCITypeRequest.ProtoReflect.Descriptor instead.
func (*GetCITypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetCITypeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCITypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiType        *CIType                `protobuf:"bytes,1,opt,name=ci_type,json=ciType,proto3" json:"ci_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCITypeResponse) Reset() {
	*x = GetCITypeResponse{}
	mi := &file_proto_cmdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCITypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCITypeResponse) ProtoMessage() {}

func (x *GetCITypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCITypeResponse.ProtoReflect.Descriptor instead.
func (*GetCITypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{5}
}

func (x *GetCITypeResponse) GetCiType() *CIType {
	if x != nil {
		return x.CiType
	}
	return nil
}

type GetCITypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCITypesRequest) Reset() {
	*x = GetCITypesRequest{}
	mi := &file_proto_cmdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCITypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCITypesRequest) ProtoMessage() {}

func (x *GetCITypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCITypesRequest.ProtoReflect.Descriptor instead.
func (*GetCITypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{6}
}

type GetCITypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiTypes       []*CIType              `protobuf:"bytes,1,rep,name=ci_types,json=ciTypes,proto3" json:"ci_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCITypesResponse) Reset() {
	*x = GetCITypesResponse{}
	mi := &file_proto_cmdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCITypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCITypesResponse) ProtoMessage() {}

func (x *GetCITypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCITypesResponse.ProtoReflect.Descriptor instead.
func (*GetCITypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{7}
}

func (x *GetCITypesResponse) GetCiTypes() []*CIType {
	if x != nil {
		return x.CiTypes
	}
	return nil
}

type GetCIRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiId          uint32                 `protobuf:"varint,1,opt,name=ci_id,json=ciId,proto3" json:"ci_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIRelationsRequest) Reset() {
	*x = GetCIRelationsRequest{}
	mi := &file_proto_cmdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIRelationsRequest) ProtoMessage() {}

func (x *GetCIRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetCIRelationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{8}
}

func (x *GetCIRelationsRequest) GetCiId() uint32 {
	if x != nil {
		return x.CiId
	}
	return 0
}

type GetCIRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*CIRelation          `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIRelationsResponse) Reset() {
	*x = GetCIRelationsResponse{}
	mi := &file_proto_cmdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIRelationsResponse) ProtoMessage() {}

func (x *GetCIRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetCIRelationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{9}
}

func (x *GetCIRelationsResponse) GetRelations() []*CIRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CIInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CiTypeId      uint32                 `protobuf:"varint,2,opt,name=ci_type_id,json=ciTypeId,proto3" json:"ci_type_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attributes    *_struct.Struct        `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CiType        *CIType                `protobuf:"bytes,8,opt,name=ci_type,json=ciType,proto3" json:"ci_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIInstance) Reset() {
	*x = CIInstance{}
	mi := &file_proto_cmdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIInstance) ProtoMessage() {}

func (x *CIInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIInstance.ProtoReflect.Descriptor instead.
func (*CIInstance) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{10}
}

func (x *CIInstance) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CIInstance) GetCiTypeId() uint32 {
	if x != nil {
		return x.CiTypeId
	}
	return 0
}

func (x *CIInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CIInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CIInstance) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CIInstance) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CIInstance) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CIInstance) GetCiType() *CIType {
	if x != nil {
		return x.CiType
	}
	return nil
}

type CIType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIType) Reset() {
	*x = CIType{}
	mi := &file_proto_cmdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIType) ProtoMessage() {}

func (x *CIType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIType.ProtoReflect.Descriptor instead.
func (*CIType) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{11}
}

func (x *CIType) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CIType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CIType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CIType) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CIType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CIType) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CIRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      uint32                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildId       uint32                 `protobuf:"varint,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	RelationType  string                 `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Parent        *CIInstance            `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	Child         *CIInstance            `protobuf:"bytes,7,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIRelation) Reset() {
	*x = CIRelation{}
	mi := &file_proto_cmdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIRelation) ProtoMessage() {}

func (x *CIRelation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIRelation.ProtoReflect.Descriptor instead.
func (*CIRelation) Descriptor() ([]byte, []int) {
	return file_proto_cmdb_proto_rawDescGZIP(), []int{12}
}

func (x *CIRelation) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CIRelation) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CIRelation) GetChildId() uint32 {
	if x != nil {
		return x.ChildId
	}
	return 0
}

func (x *CIRelation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *CIRelation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CIRelation) GetParent() *CIInstance {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *CIRelation) GetChild() *CIInstance {
	if x != nil {
		return x.Child
	}
	return nil
}

var File_proto_cmdb_proto protoreflect.FileDescriptor

const file_proto_cmdb_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cmdb.proto\x12\x04cmdb\x1a\x1cgoogle/protobuf/struct.proto\"&\n" +
	"\x14GetCIInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"E\n" +
	"\x15GetCIInstanceResponse\x12,\n" +
	"\binstance\x18\x01 \x01(\v2\x10.cmdb.CIInstanceR\binstance\"\xe6\x01\n" +
	"\x15GetCIInstancesRequest\x12\x1c\n" +
	"\n" +
	"ci_type_id\x18\x01 \x01(\rR\bciTypeId\x12B\n" +
	"\afilters\x18\x02 \x03(\v2(.cmdb.GetCIInstancesRequest.FiltersEntryR\afilters\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x16GetCIInstancesResponse\x12.\n" +
	"\tinstances\x18\x01 \x03(\v2\x10.cmdb.CIInstanceR\tinstances\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\"\n" +
	"\x10GetCITypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\":\n" +
	"\x11GetCITypeResponse\x12%\n" +
	"\aci_type\x18\x01 \x01(\v2\f.cmdb.CITypeR\x06ciType\"\x13\n" +
	"\x11GetCITypesRequest\"=\n" +
	"\x12GetCITypesResponse\x12'\n" +
	"\bci_types\x18\x01 \x03(\v2\f.cmdb.CITypeR\aciTypes\",\n" +
	"\x15GetCIRelationsRequest\x12\x13\n" +
	"\x05ci_id\x18\x01 \x01(\rR\x04ciId\"H\n" +
	"\x16GetCIRelationsResponse\x12.\n" +
	"\trelations\x18\x01 \x03(\v2\x10.cmdb.CIRelationR\trelations\"\x84\x02\n" +
	"\n" +
	"CIInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\n" +
	"ci_type_id\x18\x02 \x01(\rR\bciTypeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12%\n" +
	"\aci_type\x18\b \x01(\v2\f.cmdb.CITypeR\x06ciType\"\xa2\x01\n" +
	"\x06CIType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\xed\x01\n" +
	"\n" +
	"CIRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\rR\bparentId\x12\x19\n" +
	"\bchild_id\x18\x03 \x01(\rR\achildId\x12#\n" +
	"\rrelation_type\x18\x04 \x01(\tR\frelationType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12(\n" +
	"\x06parent\x18\x06 \x01(\v2\x10.cmdb.CIInstanceR\x06parent\x12&\n" +
	"\x05child\x18\a \x01(\v2\x10.cmdb.CIInstanceR\x05child2\xf0\x02\n" +
	"\vCMDBService\x12H\n" +
	"\rGetCIInstance\x12\x1a.cmdb.GetCIInstanceRequest\x1a\x1b.cmdb.GetCIInstanceResponse\x12K\n" +
	"\x0eGetCIInstances\x12\x1b.cmdb.GetCIInstancesRequest\x1a\x1c.cmdb.GetCIInstancesResponse\x12<\n" +
	"\tGetCIType\x12\x16.cmdb.GetCITypeRequest\x1a\x17.cmdb.GetCITypeResponse\x12?\n" +
	"\n" +
	"GetCITypes\x12\x17.cmdb.GetCITypesRequest\x1a\x18.cmdb.GetCITypesResponse\x12K\n" +
	"\x0eGetCIRelations\x12\x1b.cmdb.GetCIRelationsRequest\x1a\x1c.cmdb.GetCIRelationsResponseB%Z#github.com/itcmdb/shared/proto/cmdbb\x06proto3"

var (
	file_proto_cmdb_proto_rawDescOnce sync.Once
	file_proto_cmdb_proto_rawDescData []byte
)

func file_proto_cmdb_proto_rawDescGZIP() []byte {
	file_proto_cmdb_proto_rawDescOnce.Do(func() {
		file_proto_cmdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cmdb_proto_rawDesc), len(file_proto_cmdb_proto_rawDesc)))
	})
	return file_proto_cmdb_proto_rawDescData
}

var file_proto_cmdb_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_cmdb_proto_goTypes = []any{
	(*GetCIInstanceRequest)(nil),   // 0: cmdb.GetCIInstanceRequest
	(*GetCIInstanceResponse)(nil),  // 1: cmdb.GetCIInstanceResponse
	(*GetCIInstancesRequest)(nil),  // 2: cmdb.GetCIInstancesRequest
	(*GetCIInstancesResponse)(nil), // 3: cmdb.GetCIInstancesResponse
	(*GetCITypeRequest)(nil),       // 4: cmdb.GetCITypeRequest
	(*GetCITypeResponse)(nil),      // 5: cmdb.GetCITypeResponse
	(*GetCITypesRequest)(nil),      // 6: cmdb.GetCITypesRequest
	(*GetCITypesResponse)(nil),     // 7: cmdb.GetCITypesResponse
	(*GetCIRelationsRequest)(nil),  // 8: cmdb.GetCIRelationsRequest
	(*GetCIRelationsResponse)(nil), // 9: cmdb.GetCIRelationsResponse
	(*CIInstance)(nil),             // 10: cmdb.CIInstance
	(*CIType)(nil),                 // 11: cmdb.CIType
	(*CIRelation)(nil),             // 12: cmdb.CIRelation
	nil,                            // 13: cmdb.GetCIInstancesRequest.FiltersEntry
	(*_struct.Struct)(nil),         // 14: google.protobuf.Struct
}
var file_proto_cmdb_proto_depIdxs = []int32{
	10, // 0: cmdb.GetCIInstanceResponse.instance:type_name -> cmdb.CIInstance
	13, // 1: cmdb.GetCIInstancesRequest.filters:type_name -> cmdb.GetCIInstancesRequest.FiltersEntry
	10, // 2: cmdb.GetCIInstancesResponse.instances:type_name -> cmdb.CIInstance
	11, // 3: cmdb.GetCITypeResponse.ci_type:type_name -> cmdb.CIType
	11, // 4: cmdb.GetCITypesResponse.ci_types:type_name -> cmdb.CIType
	12, // 5: cmdb.GetCIRelationsResponse.relations:type_name -> cmdb.CIRelation
	14, // 6: cmdb.CIInstance.attributes:type_name -> google.protobuf.Struct
	11, // 7: cmdb.CIInstance.ci_type:type_name -> cmdb.CIType
	10, // 8: cmdb.CIRelation.parent:type_name -> cmdb.CIInstance
	10, // 9: cmdb.CIRelation.child:type_name -> cmdb.CIInstance
	0,  // 10: cmdb.CMDBService.GetCIInstance:input_type -> cmdb.GetCIInstanceRequest
	2,  // 11: cmdb.CMDBService.GetCIInstances:input_type -> cmdb.GetCIInstancesRequest
	4,  // 12: cmdb.CMDBService.GetCIType:input_type -> cmdb.GetCITypeRequest
	6,  // 13: cmdb.CMDBService.GetCITypes:input_type -> cmdb.GetCITypesRequest
	8,  // 14: cmdb.CMDBService.GetCIRelations:input_type -> cmdb.GetCIRelationsRequest
	1,  // 15: cmdb.CMDBService.GetCIInstance:output_type -> cmdb.GetCIInstanceResponse
	3,  // 16: cmdb.CMDBService.GetCIInstances:output_type -> cmdb.GetCIInstancesResponse
	5,  // 17: cmdb.CMDBService.GetCIType:output_type -> cmdb.GetCITypeResponse
	7,  // 18: cmdb.CMDBService.GetCITypes:output_type -> cmdb.GetCITypesResponse
	9,  // 19: cmdb.CMDBService.GetCIRelations:output_type -> cmdb.GetCIRelationsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_cmdb_proto_init() }
func file_proto_cmdb_proto_init() {
	if File_proto_cmdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cmdb_proto_rawDesc), len(file_proto_cmdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cmdb_proto_goTypes,
		DependencyIndexes: file_proto_cmdb_proto_depIdxs,
		MessageInfos:      file_proto_cmdb_proto_msgTypes,
	}.Build()
	File_proto_cmdb_proto = out.File
	file_proto_cmdb_proto_goTypes = nil
	file_proto_cmdb_proto_depIdxs = nil
}
