// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proto/cmdb.proto

package cmdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CMDBService_GetCIInstance_FullMethodName  = "/cmdb.CMDBService/GetCIInstance"
	CMDBService_GetCIInstances_FullMethodName = "/cmdb.CMDBService/GetCIInstances"
	CMDBService_GetCIType_FullMethodName      = "/cmdb.CMDBService/GetCIType"
	CMDBService_GetCITypes_FullMethodName     = "/cmdb.CMDBService/GetCITypes"
	CMDBService_GetCIRelations_FullMethodName = "/cmdb.CMDBService/GetCIRelations"
)

// CMDBServiceClient is the client API for CMDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CMDB服务
type CMDBServiceClient interface {
	// 获取CI实例
	GetCIInstance(ctx context.Context, in *GetCIInstanceRequest, opts ...grpc.CallOption) (*GetCIInstanceResponse, error)
	// 获取CI实例列表
	GetCIInstances(ctx context.Context, in *GetCIInstancesRequest, opts ...grpc.CallOption) (*GetCIInstancesResponse, error)
	// 获取CI类型
	GetCIType(ctx context.Context, in *GetCITypeRequest, opts ...grpc.CallOption) (*GetCITypeResponse, error)
	// 获取CI类型列表
	GetCITypes(ctx context.Context, in *GetCITypesRequest, opts ...grpc.CallOption) (*GetCITypesResponse, error)
	// 获取CI关系
	GetCIRelations(ctx context.Context, in *GetCIRelationsRequest, opts ...grpc.CallOption) (*GetCIRelationsResponse, error)
}

type cMDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCMDBServiceClient(cc grpc.ClientConnInterface) CMDBServiceClient {
	return &cMDBServiceClient{cc}
}

func (c *cMDBServiceClient) GetCIInstance(ctx context.Context, in *GetCIInstanceRequest, opts ...grpc.CallOption) (*GetCIInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCIInstanceResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCIInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCIInstances(ctx context.Context, in *GetCIInstancesRequest, opts ...grpc.CallOption) (*GetCIInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCIInstancesResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCIInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCIType(ctx context.Context, in *GetCITypeRequest, opts ...grpc.CallOption) (*GetCITypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCITypeResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCIType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCITypes(ctx context.Context, in *GetCITypesRequest, opts ...grpc.CallOption) (*GetCITypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCITypesResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCITypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCIRelations(ctx context.Context, in *GetCIRelationsRequest, opts ...grpc.CallOption) (*GetCIRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCIRelationsResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCIRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMDBServiceServer is the server API for CMDBService service.
// All implementations must embed UnimplementedCMDBServiceServer
// for forward compatibility.
//
// CMDB服务
type CMDBServiceServer interface {
	// 获取CI实例
	GetCIInstance(context.Context, *GetCIInstanceRequest) (*GetCIInstanceResponse, error)
	// 获取CI实例列表
	GetCIInstances(context.Context, *GetCIInstancesRequest) (*GetCIInstancesResponse, error)
	// 获取CI类型
	GetCIType(context.Context, *GetCITypeRequest) (*GetCITypeResponse, error)
	// 获取CI类型列表
	GetCITypes(context.Context, *GetCITypesRequest) (*GetCITypesResponse, error)
	// 获取CI关系
	GetCIRelations(context.Context, *GetCIRelationsRequest) (*GetCIRelationsResponse, error)
	mustEmbedUnimplementedCMDBServiceServer()
}

// UnimplementedCMDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCMDBServiceServer struct{}

func (UnimplementedCMDBServiceServer) GetCIInstance(context.Context, *GetCIInstanceRequest) (*GetCIInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCIInstance not implemented")
}
func (UnimplementedCMDBServiceServer) GetCIInstances(context.Context, *GetCIInstancesRequest) (*GetCIInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCIInstances not implemented")
}
func (UnimplementedCMDBServiceServer) GetCIType(context.Context, *GetCITypeRequest) (*GetCITypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCIType not implemented")
}
func (UnimplementedCMDBServiceServer) GetCITypes(context.Context, *GetCITypesRequest) (*GetCITypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCITypes not implemented")
}
func (UnimplementedCMDBServiceServer) GetCIRelations(context.Context, *GetCIRelationsRequest) (*GetCIRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCIRelations not implemented")
}
func (UnimplementedCMDBServiceServer) mustEmbedUnimplementedCMDBServiceServer() {}
func (UnimplementedCMDBServiceServer) testEmbeddedByValue()                     {}

// UnsafeCMDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CMDBServiceServer will
// result in compilation errors.
type UnsafeCMDBServiceServer interface {
	mustEmbedUnimplementedCMDBServiceServer()
}

func RegisterCMDBServiceServer(s grpc.ServiceRegistrar, srv CMDBServiceServer) {
	// If the following call panics, it indicates UnimplementedCMDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CMDBService_ServiceDesc, srv)
}

func _CMDBService_GetCIInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCIInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCIInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCIInstance(ctx, req.(*GetCIInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCIInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCIInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCIInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCIInstances(ctx, req.(*GetCIInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCIType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCITypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCIType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCIType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCIType(ctx, req.(*GetCITypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCITypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCITypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCITypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCITypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCITypes(ctx, req.(*GetCITypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCIRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCIRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCIRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCIRelations(ctx, req.(*GetCIRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CMDBService_ServiceDesc is the grpc.ServiceDesc for CMDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CMDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdb.CMDBService",
	HandlerType: (*CMDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCIInstance",
			Handler:    _CMDBService_GetCIInstance_Handler,
		},
		{
			MethodName: "GetCIInstances",
			Handler:    _CMDBService_GetCIInstances_Handler,
		},
		{
			MethodName: "GetCIType",
			Handler:    _CMDBService_GetCIType_Handler,
		},
		{
			MethodName: "GetCITypes",
			Handler:    _CMDBService_GetCITypes_Handler,
		},
		{
			MethodName: "GetCIRelations",
			Handler:    _CMDBService_GetCIRelations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cmdb.proto",
}
