// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_proto_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

func (x *GetAlertRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertResponse) Reset() {
	*x = GetAlertResponse{}
	mi := &file_proto_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertResponse) ProtoMessage() {}

func (x *GetAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type GetAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AffectedCiId  uint32                 `protobuf:"varint,3,opt,name=affected_ci_id,json=affectedCiId,proto3" json:"affected_ci_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsRequest) Reset() {
	*x = GetAlertsRequest{}
	mi := &file_proto_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsRequest) ProtoMessage() {}

func (x *GetAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *GetAlertsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAlertsRequest) GetAffectedCiId() uint32 {
	if x != nil {
		return x.AffectedCiId
	}
	return 0
}

func (x *GetAlertsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAlertsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	mi := &file_proto_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *GetAlertsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleRequest) Reset() {
	*x = GetAlertRuleRequest{}
	mi := &file_proto_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleRequest) ProtoMessage() {}

func (x *GetAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertRuleRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleResponse) Reset() {
	*x = GetAlertRuleResponse{}
	mi := &file_proto_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleResponse) ProtoMessage() {}

func (x *GetAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlertRuleResponse) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type GetAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRulesRequest) Reset() {
	*x = GetAlertRulesRequest{}
	mi := &file_proto_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRulesRequest) ProtoMessage() {}

func (x *GetAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlertRulesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRulesResponse) Reset() {
	*x = GetAlertRulesResponse{}
	mi := &file_proto_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRulesResponse) ProtoMessage() {}

func (x *GetAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{7}
}

func (x *GetAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AcknowledgeAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertRequest) Reset() {
	*x = AcknowledgeAlertRequest{}
	mi := &file_proto_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertRequest) ProtoMessage() {}

func (x *AcknowledgeAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{8}
}

func (x *AcknowledgeAlertRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AcknowledgeAlertRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AcknowledgeAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertResponse) Reset() {
	*x = AcknowledgeAlertResponse{}
	mi := &file_proto_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertResponse) ProtoMessage() {}

func (x *AcknowledgeAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{9}
}

func (x *AcknowledgeAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type Alert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId         uint32                 `protobuf:"varint,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Severity       string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AffectedCiId   uint32                 `protobuf:"varint,7,opt,name=affected_ci_id,json=affectedCiId,proto3" json:"affected_ci_id,omitempty"`
	TriggeredAt    string                 `protobuf:"bytes,8,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	AcknowledgedAt string                 `protobuf:"bytes,9,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	AcknowledgedBy uint32                 `protobuf:"varint,10,opt,name=acknowledged_by,json=acknowledgedBy,proto3" json:"acknowledged_by,omitempty"`
	ClosedAt       string                 `protobuf:"bytes,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{10}
}

func (x *Alert) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Alert) GetAffectedCiId() uint32 {
	if x != nil {
		return x.AffectedCiId
	}
	return 0
}

func (x *Alert) GetTriggeredAt() string {
	if x != nil {
		return x.TriggeredAt
	}
	return ""
}

func (x *Alert) GetAcknowledgedAt() string {
	if x != nil {
		return x.AcknowledgedAt
	}
	return ""
}

func (x *Alert) GetAcknowledgedBy() uint32 {
	if x != nil {
		return x.AcknowledgedBy
	}
	return 0
}

func (x *Alert) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

type AlertRule struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition            string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Severity             string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	NotificationChannels string                 `protobuf:"bytes,5,opt,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"`
	IsActive             bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_proto_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{11}
}

func (x *AlertRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AlertRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRule) GetNotificationChannels() string {
	if x != nil {
		return x.NotificationChannels
	}
	return ""
}

func (x *AlertRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_proto_alert_proto protoreflect.FileDescriptor

const file_proto_alert_proto_rawDesc = "" +
	"\n" +
	"\x11proto/alert.proto\x12\x05alert\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"6\n" +
	"\x10GetAlertResponse\x12\"\n" +
	"\x05alert\x18\x01 \x01(\v2\f.alert.AlertR\x05alert\"\x9d\x01\n" +
	"\x10GetAlertsRequest\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0eaffected_ci_id\x18\x03 \x01(\rR\faffectedCiId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"O\n" +
	"\x11GetAlertsResponse\x12$\n" +
	"\x06alerts\x18\x01 \x03(\v2\f.alert.AlertR\x06alerts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"%\n" +
	"\x13GetAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"<\n" +
	"\x14GetAlertRuleResponse\x12$\n" +
	"\x04rule\x18\x01 \x01(\v2\x10.alert.AlertRuleR\x04rule\"3\n" +
	"\x14GetAlertRulesRequest\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\"?\n" +
	"\x15GetAlertRulesResponse\x12&\n" +
	"\x05rules\x18\x01 \x03(\v2\x10.alert.AlertRuleR\x05rules\"B\n" +
	"\x17AcknowledgeAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\">\n" +
	"\x18AcknowledgeAlertResponse\x12\"\n" +
	"\x05alert\x18\x01 \x01(\v2\f.alert.AlertR\x05alert\"\xd4\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\rR\x06ruleId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\x0eaffected_ci_id\x18\a \x01(\rR\faffectedCiId\x12!\n" +
	"\ftriggered_at\x18\b \x01(\tR\vtriggeredAt\x12'\n" +
	"\x0facknowledged_at\x18\t \x01(\tR\x0eacknowledgedAt\x12'\n" +
	"\x0facknowledged_by\x18\n" +
	" \x01(\rR\x0eacknowledgedBy\x12\x1b\n" +
	"\tclosed_at\x18\v \x01(\tR\bclosedAt\"\xbb\x01\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x123\n" +
	"\x15notification_channels\x18\x05 \x01(\tR\x14notificationChannels\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive2\xf5\x02\n" +
	"\fAlertService\x12;\n" +
	"\bGetAlert\x12\x16.alert.GetAlertRequest\x1a\x17.alert.GetAlertResponse\x12>\n" +
	"\tGetAlerts\x12\x17.alert.GetAlertsRequest\x1a\x18.alert.GetAlertsResponse\x12G\n" +
	"\fGetAlertRule\x12\x1a.alert.GetAlertRuleRequest\x1a\x1b.alert.GetAlertRuleResponse\x12J\n" +
	"\rGetAlertRules\x12\x1b.alert.GetAlertRulesRequest\x1a\x1c.alert.GetAlertRulesResponse\x12S\n" +
	"\x10AcknowledgeAlert\x12\x1e.alert.AcknowledgeAlertRequest\x1a\x1f.alert.AcknowledgeAlertResponseB&Z$github.com/itcmdb/shared/proto/alertb\x06proto3"

var (
	file_proto_alert_proto_rawDescOnce sync.Once
	file_proto_alert_proto_rawDescData []byte
)

func file_proto_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)))
	})
	return file_proto_alert_proto_rawDescData
}

var file_proto_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_alert_proto_goTypes = []any{
	(*GetAlertRequest)(nil),          // 0: alert.GetAlertRequest
	(*GetAlertResponse)(nil),         // 1: alert.GetAlertResponse
	(*GetAlertsRequest)(nil),         // 2: alert.GetAlertsRequest
	(*GetAlertsResponse)(nil),        // 3: alert.GetAlertsResponse
	(*GetAlertRuleRequest)(nil),      // 4: alert.GetAlertRuleRequest
	(*GetAlertRuleResponse)(nil),     // 5: alert.GetAlertRuleResponse
	(*GetAlertRulesRequest)(nil),     // 6: alert.GetAlertRulesRequest
	(*GetAlertRulesResponse)(nil),    // 7: alert.GetAlertRulesResponse
	(*AcknowledgeAlertRequest)(nil),  // 8: alert.AcknowledgeAlertRequest
	(*AcknowledgeAlertResponse)(nil), // 9: alert.AcknowledgeAlertResponse
	(*Alert)(nil),                    // 10: alert.Alert
	(*AlertRule)(nil),                // 11: alert.AlertRule
}
var file_proto_alert_proto_depIdxs = []int32{
	10, // 0: alert.GetAlertResponse.alert:type_name -> alert.Alert
	10, // 1: alert.GetAlertsResponse.alerts:type_name -> alert.Alert
	11, // 2: alert.GetAlertRuleResponse.rule:type_name -> alert.AlertRule
	11, // 3: alert.GetAlertRulesResponse.rules:type_name -> alert.AlertRule
	10, // 4: alert.AcknowledgeAlertResponse.alert:type_name -> alert.Alert
	0,  // 5: alert.AlertService.GetAlert:input_type -> alert.GetAlertRequest
	2,  // 6: alert.AlertService.GetAlerts:input_type -> alert.GetAlertsRequest
	4,  // 7: alert.AlertService.GetAlertRule:input_type -> alert.GetAlertRuleRequest
	6,  // 8: alert.AlertService.GetAlertRules:input_type -> alert.GetAlertRulesRequest
	8,  // 9: alert.AlertService.AcknowledgeAlert:input_type -> alert.AcknowledgeAlertRequest
	1,  // 10: alert.AlertService.GetAlert:output_type -> alert.GetAlertResponse
	3,  // 11: alert.AlertService.GetAlerts:output_type -> alert.GetAlertsResponse
	5,  // 12: alert.AlertService.GetAlertRule:output_type -> alert.GetAlertRuleResponse
	7,  // 13: alert.AlertService.GetAlertRules:output_type -> alert.GetAlertRulesResponse
	9,  // 14: alert.AlertService.AcknowledgeAlert:output_type -> alert.AcknowledgeAlertResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_alert_proto_init() }
func file_proto_alert_proto_init() {
	if File_proto_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_proto_depIdxs,
		MessageInfos:      file_proto_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_proto = out.File
	file_proto_alert_proto_goTypes = nil
	file_proto_alert_proto_depIdxs = nil
}
